export enum ActionTypes {
  SIGN_UP_REQUEST = 'SIGN_UP_REQUEST',
  SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS',
  SIGN_UP_FAIL = 'SIGN_UP_FAIL',

  SIGN_IN_REQUEST = 'SIGN_IN_REQUEST',
  SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS',
  SIGN_IN_FAIL = 'SIGN_IN_FAIL',

  LOG_OUT = 'LOG_OUT',

  GET_USERS_REQUEST = 'GET_USERS_REQUEST',
  GET_USERS_SUCCESS = 'GET_USERS_SUCCESS',
  GET_USERS_FAIL = 'GET_USERS_FAIL',

  GET_USER_BY_ID_REQUEST = 'GET_USER_BY_ID_REQUEST',
  GET_USER_BY_ID_SUCCESS = 'GET_USER_BY_ID_SUCCESS',
  GET_USER_BY_ID_FAIL = 'GET_USER_BY_ID_FAIL',

  UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST',
  UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS',
  UPDATE_USER_FAIL = 'UPDATE_USER_FAIL',

  ADD_POST_REQUEST = 'ADD_POST_REQUEST',
  ADD_POST_SUCCESS = 'ADD_POST_SUCCESS',
  ADD_POST_FAIL = 'ADD_POST_FAIL',

  GET_POSTS_REQUEST = 'GET_POSTS_REQUEST',
  GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS',
  GET_POSTS_FAIL = 'GET_POSTS_FAIL',

  GET_LAST_POSTS_REQUEST = 'GET_LAST_POSTS_REQUEST',
  GET_LAST_POSTS_SUCCESS = 'GET_LAST_POSTS_SUCCESS',
  GET_LAST_POSTS_FAIL = 'GET_LAST_POSTS_FAIL',

  UPDATE_POST_REQUEST = 'UPDATE_POST_REQUEST',
  UPDATE_POST_SUCCESS = 'UPDATE_POST_SUCCESS',
  UPDATE_POST_FAIL = 'UPDATE_POST_FAIL',

  DELETE_POST_REQUEST = 'DELETE_POST_REQUEST',
  DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS',
  DELETE_POST_FAIL = 'DELETE_POST_FAIL',

  ADD_COMMENT_REQUEST = 'ADD_COMMENT_REQUEST',
  ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS',
  ADD_COMMENT_FAIL = 'ADD_COMMENT_FAIL',

  GET_COMMENTS_BY_POST_ID_REQUEST =
    'GET_COMMENTS_BY_POST_ID_REQUEST',
  GET_COMMENTS_BY_POST_ID_SUCCESS =
    'GET_COMMENTS_BY_POST_ID_SUCCESS',
  GET_COMMENTS_BY_POST_ID_FAIL = 'GET_COMMENTS_BY_POST_ID_FAIL',

  GET_COMMENTS_REQUEST = 'GET_COMMENTS_REQUEST',
  GET_COMMENTS_SUCCESS = 'GET_COMMENTS_SUCCESS',
  GET_COMMENTS_FAIL = 'GET_COMMENTS_FAIL',

  INC_COUNTER = 'INC_COUNTER',
}

